elk:
    #image: willdurand/elk
    build: .
    ports:
        - "5601:5601"   # kibana
        - "514:514"     # syslog
        - "9200:9200"   # elasticsearch
    volumes:
        - ./etc:/data/etc
        - ./opt:/data/opt
        - /data/elk/log/logstash:/var/log/logstash
        - /data/elk/log/elasticsearch:/var/log/elasticsearch
    volumes_from:
        - dataelk

dataelk:
    image: busybox
    volumes:
        - /data/elk
